# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_OPTIONS: --max-old-space-size=2048

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 21.x]
 
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache ESLint
      id: cache-eslint
      uses: actions/cache@v4
      with:
        path: .eslintcache
        key: ${{ matrix.platform }}-${{ matrix.node-version }}-eslint
    - run: npm ci
    - run: cp src/config-example.ts src/config.ts
    - run: npm run test
